language: rust

rust:
  - stable
  - beta
  - nightly
  
matrix:
    allow_failures:
      - rust: nightly

addons:
    apt:
        packages:
          - build-essential
          - libgl1-mesa-dev
          - x11proto-core-dev
          - libx11-dev
