[package]
name = "00-helloworld"
version = "0.1.0"
authors = ["Johan Sköld <johan@skold.cc>"]

[[bin]]
name = "00-helloworld"
path = "main.rs"

[dependencies.bgfx]
path = "../../"

[dependencies.common]
path = "../common/"
