[package]
name = "examples"
version = "0.1.0"
authors = ["Johan Sköld <johan@skold.cc>"]

[dependencies]
cgmath = "0.7.0"
glfw = "0.2.0"
libc = "0.2.4"
time = "0.1.33"

[dependencies.bgfx]
path = "../"
